//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySallary
    {
        public int Id { get; set; }
        public int Month { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int UserProfileId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
